import streamlit as st

st.title("CYK algorithm")

# input = st.text_input("Enter the no. of rules:" , "Write here...")

user_input = st.number_input("Enter the no. of rules:", min_value=0, max_value=10,
                              value=1, step=1)

st.write("You entered:", int(user_input))

st.info("NOTE: CFG should be in Chomsky Normal Form")
st.warning("INPUT FORMAT : S a,AB represents S -> a|AB")

grammars = []
for i in range(int(user_input)):
        text_input = st.text_input(f"Enter Rule {i+1}:", "")
        grammars.append(text_input)

string = st.text_input(f"Enter the string to check by CYK algorithm:", "")

def cyk_algorithm(grammar, string):
    n = len(string)

    # Create a table to store results of subproblems
    table = [[set() for _ in range(n)] for _ in range(n)]

    # Fill table using bottom-up approach
    for j in range(n):
        for rule in grammar:
            for production in grammar[rule]:
                if len(production) == 1 and production[0] == string[j]:
                    table[j][j].add(rule)

        for i in range(j - 1, -1, -1):
            for k in range(i, j):
                for rule in grammar:
                    for production in grammar[rule]:
                        if len(production) == 2 and production[0] in table[i][k] and production[1] in table[k + 1][j]:
                            table[i][j].add(rule)

    st.subheader("CYK table:")
    for row in table:
        print(row)

    st.table(table)
        # print(type(row))

    # If the start symbol is in the top-right corner, the string is generated by the grammar
    return 'S' in table[0][n - 1]

def get_grammar():
    grammar = {}
    # num_rules = int(input("Enter the number of rules: "))
    for i in range(user_input):
        non_terminal, productions = grammars[i].split()
        # productions[i] = productions[i].split(',')
        l=productions.split(',')
        grammar[non_terminal] = l
    return grammar

if __name__ == "__main__":
    grammar = get_grammar()
    # string = input("Enter the string to check: ")
    result = cyk_algorithm(grammar, string)
    if result:
        st.success("The string is generated by the grammar.")
    else:
        st.error("The string is not generated by the grammar.")    

    
    






 